name: Blog Workflow

on:
  push:
    branches:
      - hexo

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configuration Environment
        env:
          ID_ED25519: ${{secrets.ed25519}}
        run: |
          mkdir -p ~/.ssh
          echo "$ID_ED25519" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/know_hosts
          git config --global user.name 'WincerChan'
          git config --global user.email 'WincerChan@gmail.com'
      - name: Decrypt File
        env:
          PASSWD: ${{secrets.PASSWD}}
        run: |
          dd if=encrypt.des3 | openssl des3 -d -pass pass:$PASSWD | tar zxf -
          mv encrypt/* source/_posts/
      - name: Install dependencies
        run: |
          npm -i yarn -g
          yarn global add gulp
          yarn install && gulp
      - name: Deploy to VPS
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_IP: ${{secrets.SSH_IP}}
          SSH_PORT: ${{secrets.SSH_PORT}}
        run: |
          { ssh-keyscan -p $SSH_PORT $SSH_IP 2> /dev/null; } >> ~/.ssh/known_hosts
          rsync -az -v --delete -e "ssh -p $SSH_PORT" public/* $SSH_USER@$SSH_IP:/data/www/hexo/
          